# Generated by Django 5.1.2 on 2024-11-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0002_user_remove_patient_email_remove_patient_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='VibrantMind_User',
        ),
    ]
