# Generated by Django 5.1.2 on 2024-11-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0005_remove_patient_user_patient_email_patient_firstname_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VibrantMind_Account',
            new_name='Users',
        ),
    ]
