# Generated by Django 5.1.2 on 2024-11-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0006_rename_vibrantmind_account_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
