# Generated by Django 5.1.2 on 2024-11-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0008_remove_patient_email_remove_patient_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='dateRequested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
