# Generated by Django 5.1.2 on 2024-11-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0009_appointmentrequest_daterequested_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
    ]
