# Generated by Django 5.1.2 on 2024-11-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0010_delete_appointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dateRequested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
