# Generated by Django 5.1.2 on 2024-11-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0013_alter_patient_gender_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=50, null=True),
        ),
    ]
