# Generated by Django 5.1.2 on 2024-11-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0018_userprofile_alter_patient_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('health services', 'Health Services'), ('counceling services', 'Counceling Services')], max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
