# Generated by Django 5.1.2 on 2024-11-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0020_alter_appointment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('health_services', 'Health Services'), ('counceling_services', 'Counceling Services')], max_length=100),
        ),
    ]
