# Generated by Django 5.1.2 on 2024-11-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0027_alter_appointment_patient_alter_patient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
