# Generated by Django 5.1.2 on 2024-11-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0028_alter_appointment_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Health Services', 'Health Services'), ('Counceling Services', 'Counceling Services')], max_length=100, null=True),
        ),
    ]
