# Generated by Django 5.1.2 on 2024-11-28 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0031_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('Health Service', 'Health Service'), ('Counceling Service', 'Counceling Service')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('Face-to-face', 'Face-to-Face'), ('Online', 'Online')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('Health Consultant', 'Health Consultant'), ('Councelor', 'Councelor')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VibrantMind_app.userprofile')),
            ],
        ),
    ]
