# Generated by Django 5.1.2 on 2024-12-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0033_userprofile_email_alter_userprofile_age_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timeRequested',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateRequested',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
