# Generated by Django 5.1.2 on 2024-12-11 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0044_remove_patient_age_remove_patient_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VibrantMind_app.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
