# Generated by Django 5.1.2 on 2024-12-11 00:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0045_remove_prescription_user_prescription_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
