# Generated by Django 5.1.2 on 2024-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0049_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='date_prescribed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
