# Generated by Django 5.1.2 on 2024-12-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0051_remove_healthrecord_medical_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='address',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='emergency_contact_relationship',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
