# Generated by Django 5.1.2 on 2024-12-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibrantMind_app', '0052_remove_healthrecord_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='VibrantMind_app.patient'),
        ),
    ]
