# Generated by Django 4.2.16 on 2024-09-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentschedulingmodel',
            name='contactNum',
        ),
        migrations.RemoveField(
            model_name='appointmentschedulingmodel',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='appointmentschedulingmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointmentschedulingmodel',
            name='time',
            field=models.TimeField(),
        ),
    ]
