# Generated by Django 5.1.1 on 2024-09-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedulingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contactNum', models.CharField(max_length=11)),
                ('staff', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
